name: "action-123"
#inputs:

#outputs:

execute_commands:
  - "echo 123;"

#tabs:

#volume_mappings:
#  -

#working_directory: ""

#cached_dirs:
#  - ""
docker_image_name: "ubuntu"
docker_image_tag: "latest"
